# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class EmailVerificationRequested(BaseModel):
    login: "EmailVerificationRequestedLogin"


class EmailVerificationRequestedLogin(BaseModel):
    typename__: Literal["IQueryableLogin", "QueryableLogin"] = Field(alias="__typename")
    username: Optional[str]
    email: Optional["EmailVerificationRequestedLoginEmail"]


class EmailVerificationRequestedLoginEmail(BaseModel):
    typename__: Literal["IQueryableEmail", "QueryableEmail"] = Field(alias="__typename")
    address: str
    verify_token: Optional[str] = Field(alias="verifyToken")


EmailVerificationRequested.model_rebuild()
EmailVerificationRequestedLogin.model_rebuild()
